[package]
name = "brainbox"
version = "0.1.0"
edition = "2021"

[dependencies]

uuid = { version = "1.10.0", features = ["v4"] }
eframe = "0.29.1"
egui = "0.29.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
